### ISSUE TITLE
Communication проект для Accounts

### ISSUE THREAD

**Issue by KirillSachkov** [SachkovTech/sachkov-tech-backend#94]
По аналогии с FileService написать Communication проект для аккаунтов.
Нужно два метода

1. Получить всю инфу о пользователе по Id
2. Получить всю информацию о пользователях по Ids (этот метод нужно написать - Входные параметры 
[FromBody] IEnumerable<Guid> Ids - метод должен быть POST, потому что коллекция Ids)
3. Вынести проект в nuget по аналогии с FilesService

**Comment by aznoran** [comment]
отмена я не буду это делать но сделал базу дальше сами
